import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from '@next/third-parties/google'
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
      <GoogleTagManager gtmId="GTM-P5DSX4XJ" />
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P5DSX4XJ"
      height="0" width="0" style={{display:"none", visibility:"hidden"}}></iframe></noscript>
      <body className="font-poppins">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
